version: '3.7'

services:
  renascer-api:
    image: postgres:11-alpine
    restart: always
    container_name: renascer-api
    ports:
      - 3333:5432
    environment:
      POSTGRES_DB: renascer-api
      POSTGRES_USER: renascer
      POSTGRES_PASSWORD: renascer