INSERT INTO public.video (video_id, youtube_frame, title, author, description, "date", cover_image, category, notified)
VALUES
    (
        'zKKDbgVMN6s',
        'https://www.youtube.com/embed/zKKDbgVMN6s?si=K6lJasD_cMwxKMOS',
        'PENTECOSTES',
        'Ap. Marcio Ribeiro',
        'Série de mensagens Pentecostes.',
        '2024-08-18 19:00:00.000',
        '',
        'PENTECOSTES',
        false
    ),
    (
        'zDDYgfjyRZ4',
        'https://www.youtube.com/embed/zDDYgfjyRZ4?si=K6lJasD_cMwxKMOS',
        'PENTECOSTES',
        'Ap. Marcio Ribeiro',
        'Série de mensagens Pentecostes.',
        '2024-08-11 19:00:00.000',
        '',
        'PENTECOSTES',
        true
    ),
    (
        'fisiWxyiuF0',
        'https://www.youtube.com/embed/fisiWxyiuF0?si=K6lJasD_cMwxKMOS',
        'PENTECOSTES',
        'Pr. Vandinho Soares',
        'Série de mensagens Pentecostes.',
        '2024-08-04 19:00:00.000',
        '',
        'PENTECOSTES',
        true
    ),
    (
        'XY4nXLmh4zs',
        'https://www.youtube.com/embed/XY4nXLmh4zs?si=K6lJasD_cMwxKMOS',
        'TRILHA DE MATURIDADE',
        'Ap. Marcio Ribeiro',
        'Série de mensagens Trilha de Maturidade.',
        '2024-07-28 19:00:00.000',
        '',
        'TRILHA_DE_MATURIDADE',
        true
    ),
    (
        'W07krfcWQIw',
        'https://www.youtube.com/embed/W07krfcWQIw?si=K6lJasD_cMwxKMOS',
        'TRILHA DE MATURIDADE',
        'Ap. Marcio Ribeiro',
        'Série de mensagens Trilha de Maturidade.',
        '2024-07-21 19:00:00.000',
        '',
        'TRILHA_DE_MATURIDADE',
        true
    ),
    (
        'TPllGyUE3IA',
        'https://www.youtube.com/embed/TPllGyUE3IA?si=K6lJasD_cMwxKMOS',
        'TRILHA DE MATURIDADE',
        'Ap. Marcio Ribeiro',
        'Série de mensagens Trilha de Maturidade.',
        '2024-07-14 19:00:00.000',
        '',
        'TRILHA_DE_MATURIDADE',
        true
    ),
    (
        'RDgJaTCXAfA',
        'https://www.youtube.com/embed/RDgJaTCXAfA?si=qdf66Or4K_lrI1WQ',
        'TRILHA DE MATURIDADE',
        'Pr. Vandinho Soares',
        'Série de mensagens Trilha de Maturidade.',
        '2024-07-07 19:00:00.000',
        '',
        'TRILHA_DE_MATURIDADE',
        true
    ),
    (
        '951N4pOvmCo',
        'https://www.youtube.com/embed/951N4pOvmCo?si=aPmqLOpRMmrsfF0H',
        'LEGADO ',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-06-30 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'Jaszwhuppgo',
        'https://www.youtube.com/embed/Jaszwhuppgo?si=v0mk33VsSd8c9U27',
        'FIM DE SEMANA PROFÉTICO',
        'Pr. Marlon Borba',
        'Culto profético.',
        '2024-06-23 19:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        'wix02ZNHcNc',
        'https://www.youtube.com/embed/wix02ZNHcNc?si=GG94Mzq_i9ysHXAn',
        'FIM DE SEMANA PROFÉTICO',
        'Profeta Tiago Ribeiro',
        'Culto profético.',
        '2024-06-22 19:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        'QXEAG4OloHU',
        'https://www.youtube.com/embed/QXEAG4OloHU?si=CciE16uKucLtKwG_',
        'CORAÇÃO NO LUGAR CERTO',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-06-16 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'FIJn_QQE1No',
        'https://www.youtube.com/embed/FIJn_QQE1No?si=7dKy1RPlBoxDaEKz',
        'UMA FAMÍLIA CHEIA DE GRAÇA',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-06-09 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '4vlpAAfRTbY',
        'https://www.youtube.com/embed/4vlpAAfRTbY?si=cNECXHEU4-mjnO62',
        'O PODER DA ORAÇÃO',
        'Pr. Vandinho Soares',
        'Culto da familia.',
        '2024-06-02 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '0mlAUJowBLY',
        'https://www.youtube.com/embed/0mlAUJowBLY?si=Tv8KO3wUniYlZqMW',
        'O QUE NÃO PODE FALTAR ?',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-05-26 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'NkSL0Vtt2ck',
        'https://www.youtube.com/embed/NkSL0Vtt2ck?si=0O0xI95GPuXzBklD',
        'FORJADO NO FOGO',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-05-19 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'sZRDOYsTzj0',
        'https://www.youtube.com/embed/sZRDOYsTzj0?si=Kcvb8ARN95O4i6MX',
        'HERDEIROS DAS CHAVES DOS CÉUS',
        'Ap. Marcio Ribeiro',
        'Culto da familia.',
        '2024-05-12 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'toPjNQokvAw',
        'https://www.youtube.com/embed/toPjNQokvAw?si=s8nQU_1cGN998E9B',
        'A UNÇÃO DO ROMPIMENTO',
        'Pr. Vandinho Soares',
        'Culto da familia.',
        '2024-05-05 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'EMqNaMsiTY4',
        'https://www.youtube.com/embed/EMqNaMsiTY4?si=2ZG7ybLFfqB2vsQT',
        'QUANDO O MINISTÉRIO PROFÉTICO TOCA A VIDA DIÁRIA',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-04-28 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'cxUmJ2jPRdA',
        'https://www.youtube.com/embed/cxUmJ2jPRdA?si=t58X2PahEBMSLTJQ',
        'UMA IGREJA ATIVADA PELO ESPÍRITO SANTO',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-04-21 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'q2olQh7XBlE',
        'https://www.youtube.com/embed/q2olQh7XBlE?si=XHlw_lBwIPMjXR1v',
        'NOITE PROFÉTICA',
        'Profeta Luis López',
        'Culto da familia.',
        '2024-04-19 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'XSG5hXzDsvg',
        'https://www.youtube.com/embed/XSG5hXzDsvg?si=u6NjI6uCTVu1Gml9',
        'ESCOLHAS DE CURA',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-04-14 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'l4ZzXQ9tb4M',
        'https://www.youtube.com/embed/l4ZzXQ9tb4M?si=YM6YXFTOnxqPffCo',
        'ANTES PERDIDO AGORA ENVIADO',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-03-31 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'mjRoqr9wPmE',
        'https://www.youtube.com/embed/mjRoqr9wPmE?si=LR-SqVppPoFSl6B_',
        'FÉ PESSOAL E RELACIONAL',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-03-24 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'MPEtnLKiU8Y',
        'https://www.youtube.com/embed/MPEtnLKiU8Y?si=9UAkppSdwEY9DF-Q',
        'CHAMAS PARA UM AVIVAMENTO',
        'Pr. Vandinho Soares',
        'Culto da familia.',
        '2024-03-17 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '51w8kNHUOy8',
        'https://www.youtube.com/embed/51w8kNHUOy8?si=nJXYWcUVbTFaBGnQ',
        'O AVIVAMENTO QUE PRECISAMOS',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-03-10 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'djYcWim9EjU',
        'https://www.youtube.com/embed/djYcWim9EjU?si=Z6Pk-lEYibcfMGiV',
        'VENCENDO AS DIFICULDADES',
        'Pra. Inês Brustulin',
        'Culto da familia.',
        '2024-03-03 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '383p4ids6qo',
        'https://www.youtube.com/embed/383p4ids6qo?si=wVK6YOtadYU7RwbO',
        'QUEM VOCÊ PENSA QUE É?',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-03-02 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'yEtBqbxZVxo',
        'https://www.youtube.com/embed/yEtBqbxZVxo?si=CAQNOkDBatgDDwYJ',
        'O PLANO PERFEITO DO PAI',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-02-25 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '7jNA2Dl96-8',
        'https://www.youtube.com/embed/7jNA2Dl96-8?si=_gbQ4VXp3aMVL8tJ',
        'ENCONTROS COM DEUS QUE NOS MARCAM',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-02-18 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'tdgFtL4R38w',
        'https://www.youtube.com/embed/tdgFtL4R38w?si=dNdzdf4_yuSONEwi',
        'QUANDO JESUS TOCA EM VOCÊ',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-02-11 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'KGsZcRK6WIA',
        'https://www.youtube.com/embed/KGsZcRK6WIA?si=n4z4S9SH740xDwOA',
        'ONDE EU CAÍ ?',
        'Pra. Eunice Lea',
        'Culto da familia.',
        '2024-02-04 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'vBZIWWvL0bM',
        'https://www.youtube.com/embed/vBZIWWvL0bM?si=sW0Ez0pb7V33aVAC',
        'ENTRE A FÉ E A INCREDULIDADE',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-01-28 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'u-B2TpKClOA',
        'https://www.youtube.com/embed/u-B2TpKClOA?si=8hSEcHIuMLMZW9P3',
        'MILAGRES DO JORDÃO',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-01-21 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        '7oLT-PCS5Ww',
        'https://www.youtube.com/embed/7oLT-PCS5Ww?si=1JVh7di-bVJyiDj8',
        'SOBRENATURAL UM CHAMADO PARA TODOS',
        'Pr. Sênior Marcio Ribeiro',
        'Culto da familia.',
        '2024-01-14 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'xFmiOEYg5Us',
        'https://www.youtube.com/embed/xFmiOEYg5Us?si=jofzFnizfHPWIu7Q',
        'ESPERANÇA PARA O NOVO TEMPO',
        'Pr. Willian Grossi',
        'Culto da familia.',
        '2024-01-07 19:00:00.000',
        '',
        'FAMILY',
        true
    ),
    (
        'YIKKOdK4TyI',
        'https://www.youtube.com/embed/YIKKOdK4TyI?si=pDvuukXzqQPdlPbY',
        'SESSÃO 3 - CONFERÊNCIA ÁGUAS PROFUNDAS',
        'Ap. Israel Onoriobe',
        'Conferência Águas Profundas',
        '2023-10-15 19:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        'SRBp1o3Pk0M',
        'https://www.youtube.com/embed/SRBp1o3Pk0M?si=xArjrec-cnNKUSjK',
        'SESSÃO 2 - CONFERÊNCIA ÁGUAS PROFUNDAS',
        'Pr. Vandinho Soares',
        'Conferência Águas Profundas',
        '2023-10-15 09:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        '6d-PxNI2dOo',
        'https://www.youtube.com/embed/6d-PxNI2dOo?si=Vasw7LT2A7YqslYt',
        'SESSÃO 1 - CONFERÊNCIA ÁGUAS PROFUNDAS',
        'Pr. Vandinho Soares',
        'Conferência Águas Profundas',
        '2023-10-14 19:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        'W2oZSxM1LTg',
        'https://www.youtube.com/embed/W2oZSxM1LTg?si=I_oJumy3DoGNXe3N',
        'DESENVOLVENDO A SALVAÇÃO',
        'Leonardo Jesuscopy',
        'Última ministração do acampamento da Rede Conecte.',
        '2023-07-23 19:00:00.000',
        '',
        'CONFERENCE',
        true
    ),
    (
        '7Iuc-grMhu4',
        'https://www.youtube.com/embed/7Iuc-grMhu4?si=Tbs3clP0xAAeS3aA',
        'CONFERÊNCIA ÁGUAS PROFUNDAS',
        'Pr. Cris Batiston',
        'Conferência Águas Profundas com o Pr. Cris Batiston do Ministério Filhos do Homem',
        '2023-08-14 19:00:00.000',
        '',
        'CONFERENCE',
        true
    );
